function tl(n){return Number(n||0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})}function num(id){return parseFloat(document.getElementById(id)?.value)||0}function val(id){return document.getElementById(id)?.value||''}function out(id,html){document.getElementById(id).innerHTML=html}function daysBetween(a,b){return Math.max(0,Math.ceil((new Date(b)-new Date(a))/86400000))}function addYears(s,y){let d=new Date(s);d.setFullYear(d.getFullYear()+y);return d.toISOString().slice(0,10)}function isWeekend(d){let x=d.getDay();return x===0||x===6}function fmtDate(d){return new Date(d).toLocaleDateString('tr-TR')}function calcIncomeTax(base){let t=0;if(base<=190000)t=base*.15;else if(base<=400000)t=28500+(base-190000)*.20;else if(base<=1500000)t=70500+(base-400000)*.27;else if(base<=5300000)t=367500+(base-1500000)*.35;else t=1697500+(base-5300000)*.40;return t}function monthlyTax(gross,cumBefore,minGross=33030){let emp=gross*.15,base=Math.max(0,gross-emp),taxTotal=calcIncomeTax(cumBefore+base)-calcIncomeTax(cumBefore),minTax=calcIncomeTax(minGross*.85)-calcIncomeTax(0);return Math.max(0,taxTotal-minTax)}function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}

document.addEventListener('DOMContentLoaded',function(){const nav=document.querySelector('.nav');if(!nav)return;const defs=[
['Gün & Puantaj',[['ik_operasyon_merkezi.html','🧭 İK Günlük Operasyon Merkezi'],['sgk_gun_hesapla.html','📅 SGK Gün Hesabı'],['subat_bordro_sihirbazi.html','🗓️ Şubat Bordro Sihirbazı'],['rapor_bordro.html','🏥 Rapor / Bordro'],['eksik_gun_sihirbazi.html','🧩 Eksik Gün Sihirbazı'],['kismi_calisma.html','🕒 Kısmi Çalışma Gün'],['izin_rapor_cakisma.html','🌴 İzin / Rapor Çakışması'],['hafta_tatili_rapor.html','📆 Hafta Tatili + Rapor'],['ubgt_ucret.html','🎉 UBGT Ücret Kontrolü'],['gece_vardiya_denetcisi.html','🌙 Gece / Vardiya Denetimi']]],
['Denetim & Mutabakat',[['bordro_kontrol.html','🔎 Bordro Denetimi'],['puantaj_bordro_kontrol.html','🔁 Puantaj ↔ Bordro'],['bordro_banka_mutabakat.html','🏦 Bordro ↔ Banka'],['odeme_kalemi_siniflandirici.html','🏷️ Ödeme Kalemi'],['tesvik_risk_denetcisi.html','🛡️ Teşvik Risk Denetçisi'],['maas_neden_degisti.html','📉 Maaş Neden Değişti?'],['bordro_ay_kapanis.html','✅ Bordro Ay Kapanışı'],['excel_veri_temizleme.html','🧹 Excel Veri Temizleme'],['excel_sablonlari.html','📦 Excel Şablonları']]],
['Bütçe & Analiz',[['personel_butcesi.html','📊 Personel Bütçesi'],['ik_kpi.html','📊 İK KPI'],['ik_karar_merkezi.html','🧠 İK Karar Merkezi'],['ik_maliyet_karar.html','⚖️ Maliyet Karar Simülatörü'],['ucret_beyan_kontrol.html','🧾 Ücret Beyan Kontrolü']]],
['İş Hukuku & Takvim',[['ise_giris_cikis_sure.html','🗓️ İşe Giriş / Çıkış Süresi'],['izin_suresi_hesapla.html','📅 İzin Süresi Hesabı'],['is_kazasi_bildirim_sure.html','🚨 İş Kazası Süre Kontrolü']]],
['SGK & Teşvik',[['tesvik_optimizasyon.html','⚙️ Teşvik Karar Motoru'],['tesvik_firsat_tarama.html','🔍 Teşvik Fırsat Taraması'],['tesvik_risk_denetcisi.html','🛡️ Teşvik Risk Denetçisi']]]
];
function ensureGroup(title,links){let g=[...nav.querySelectorAll('.group')].find(x=>x.textContent.trim()===title);const anchor=g?g.nextSibling:null;if(!g){g=document.createElement('div');g.className='group';g.textContent=title;let ref=[...nav.children].find(x=>x.classList&&x.classList.contains('group')&&x.textContent.trim()==='Bilgi');nav.insertBefore(g,ref||null);}let cursor=g.nextSibling;links.forEach(([href,label])=>{if(nav.querySelector('a[href="'+href+'"]'))return;const a=document.createElement('a');a.href=href;a.textContent=label;nav.insertBefore(a,cursor);});}
defs.forEach(d=>ensureGroup(d[0],d[1]));});
function printReport(title,html){const w=window.open('','_blank','width=900,height=700');if(!w)return;w.document.write('<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>'+esc(title)+'</title><style>body{font-family:Arial,sans-serif;padding:24px;color:#111}h1{color:#000080}.box{border:1px solid #999;padding:12px;margin:8px 0}</style></head><body><h1>'+esc(title)+'</h1><div class="box">'+html+'</div></body></html>');w.document.close();w.focus();w.print();}
